version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
        path: _test\.go
    paths:
      - ent
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - ent
      - third_party$
      - builtin$
      - examples$
